### ISSUE TITLE
Can a casper node run on IPv6 only ?

### ISSUE THREAD

**Issue by abdulgig** [casper-network/casper-node#1597]

**Comment by piotr-dziubecki** [comment]
hi @abdulgig, we will take care of this request. The updates will be visible in this ticket. CC @EdHastingsCasperLabs

**Comment by abdulgig** [comment]
@piotr-dziubecki Thank you

**Comment by cspramit** [comment]
Please add description if you can?

**Comment by abdulgig** [comment]
@cspramit , sorry I am not sure what description to add as the question is pretty straight forward

I have an IPv6 network. Is it possible for casper node to run on an IPv6 network ?

**Comment by cspramit** [comment]
@abdulgig - its an ask for internal developers sorry for confusion

**Comment by marc-casperlabs** [comment]
Hello @abdulgig, thanks for filing this issue.

If you want to run a casper-node on mainnet and have IPv6 networking _only_, the direct answer is no. We do not require validators to set up IPv6 connectivity of their own, so if you are an IPv6-only node on mainnet, you will have no IPv4 to pass to other nodes to connect back to you, and they will only supply you with an IPv4 address of their own.

There may be workarounds for this case involving setting up your operating system to transparently tunnel outgoing IPv4 connections to the respective IPv6 address, and we do support explicitly setting the advertised IPv4 address on the network should your ISP offer service for this, but this is not a recommended way to run a node and largely untested.

Running a private network on an IPv6-only chain may be possible, although it may require changes. Officially it is not a supported feature yet though, which is why it does not see the intensive testing we do for regular releases and thus I have to recommend to get a regular IPv4 instead.

**Comment by abdulgig** [comment]
@marc-casperlabs Thank you for a comprehensive response ! Allow me to evaluate other options
