### ISSUE TITLE
Random node crashing in small network

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#1799]
Gist: in a small network with time nodes are randomly crashing - primarily non-validating nodes, but validating as well.

https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1627457110129000

**Comment by fizyk20** [comment]
So, according to more tests ran by Ajit, this seems to be caused by AWS instance management:
https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1627553037149800?thread_ts=1627457110.129000&cid=C01ULKL8G8J
https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1627558607150500?thread_ts=1627457110.129000&cid=C01ULKL8G8J

**Comment by cspramit** [comment]
Explanation needed why AWS changes IP

**Comment by cspramit** [comment]
@thamps-casp please confirm - why AWS changes IP

**Comment by thamps-casp** [comment]
I have notified AWS regarding the adhoc reboot of random instance(s). I have not received valid reasons from AWS support at this stage.

Assessments into the intance points to EBS (AWS Elastic Block Storage) errors in kernel logs, which points to AWS underlying subsystems thats manage an instance storage. The filesystem fix is causing reboot on an instance.

We have not experienced any such disruptions lately, but have setup alerts via Kibana/Slack to notify '_node crash_' if detected in logs.

**Comment by thamps-casp** [comment]
Also to confirm that - an AWS instance changes it public IP when an instance is restarted. This is as-per AWS way of working. We use Private IPs to run our internal test networks, so the IP is persistant across restarts/reboots.

In this particular scenario, it is the underlying EBS changes that causes instances to restart. but the node will continue to service over the Private IP only as per set config.

We have not been seeing this issue in recent runs, which indicates that the issue is not recurring from underying AWS Elastic Block Storage. 

@cspramit

**Comment by cspramit** [comment]
@thamps-casp closing this - if any objection please comment
