### ISSUE TITLE
Add npm audit to CI

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1802]
Add an `npm audit` step to CI with a path filter to trigger only when an AssemblyScript code is changed.

**Comment by Fraser999** [comment]
I think we should have this as a Makefile target.  The existing `audit` Makefile target should be renamed to `audit-rs`, and similarly `setup-audit` -> `setup-audit-rs`.

The drone file should then have its `cargo-audit` step updated to use these renamed Makefile targets, and a new step (something like `npm-audit`) added.  I think it should run unconditionally, since it could fail even if no AssemblyScript code was changed.

**Comment by bradjohnl** [comment]
So for me it seems to be working. I am clarifying some things with Michal....Do we want it to fail if some conditions are met? Or do we keep it  as informative?

**Comment by bradjohnl** [comment]
https://github.com/casper-network/casper-node/pull/2663 which addresses this issue has been closed.
