### ISSUE TITLE
Express gas counter as u64

### ISSUE THREAD

**Issue by mpapierski** [casper-network/casper-node#1818]
We can safely assume that the gas limit will not exceed `u64::MAX`, and therefore we can make the gas counter represented in `u64` instead of the current `U512`. This also means we can express `Gas` new type as `u64` to simplify the code further.

This topic came up while discussing #1241 (https://github.com/casper-network/casper-node/pull/1241#issuecomment-885503490).

**Comment by goral09** [comment]
I suggest that instead of jumping between Wasm & host on every Wasm opcode, we inject a local (global) variable into the smart contract, in the preprocess phase, equal to the gas bought, and modify that contract so that instead of calling `contract_ffi::charge_gas` (that forwards to the host) would modify that local, contract variable and fail if that value goes below 0 we fail the execution.
