### ISSUE TITLE
Reenable gossip table benchmark

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1820]
CC @Fraser999

**Comment by Fraser999** [comment]
In a recent move to get the bulk of our code off nightly, the [gossip table's benchmark test](https://github.com/casper-network/casper-node/blob/dev/node/src/components/gossiper/gossip_table.rs#L1056-L1078) was commented out.

It should be re-enabled using `criterion` so that it can be built using stable Rust.

**Comment by rafal-ch** [comment]
It is currently not possible to test private interface with the `criterion` framework.

As agreed with @Fraser999, I'll remove this benchmark at all.
