### ISSUE TITLE
Investigate how the testnet nodes are being made aware of the mainnet nodes' addresses

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1833]

**Comment by marc-casperlabs** [comment]
Currently working as intended. 1.0 nodes do not disconnect from higher version nodes, as they lack this feature, so an old node at 1.0 that does not shut down due to not upgrading will never disconnect on its own. At the same time, newer nodes will always allow earlier versions to connect, as they may be asking for data to upgrade.

Overall this problem could only be curbed by newer nodes restricting some of the traffic from the older nodes, but this situation should resolve itself with the arrival of fastsync.

**Comment by cspramit** [comment]
@marc-casperlabs @Fraser999  as discussed more investigation needed

**Comment by piotr-dziubecki** [comment]
@sacherjj @marc-casperlabs is this still happening?

**Comment by marc-casperlabs** [comment]
I don't know, as I usually do not have these statistics available from testnet/mainnet :)
