### ISSUE TITLE
Don't Request All The Latest States From All Of The Peers At Once

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#1914]
Currently a node waits for the whole `standstill_alert` and then requests the latest state from _all_ peers. That means it will fail to make progress for a long time and then send way too many messages (small ones, fortunately).

We should instead have a shorter timeout for this and periodically request the latest state from just one peer. Maybe even unconditionally, just to add another source.

**Comment by afck** [comment]
I was going to use `NetworkInfoRequest::GetPeersInRandomOrder` from the `feat-fast-sync` branch, but it seems a bit wasteful, since I want to send a message to only one random peer at a time. Is it better to add a `GetRandomPeer` request or `SendMessageToRandomPeer`?

I'd also separate the `standstill_timeout` from the `request_state_interval` then:

* The former would be optional, and _only_ be used for the restart, so we could get rid of the separate `restart_on_standstill` boolean, and maybe rename this one to `restart_on_standstill_timeout`? If it's present, a node would restart according to the current rules: if in the era where it joined it fails to make progress for that long.
* The latter would be configured to something much smaller, e.g. 10 seconds, and the node would unconditionally request the latest state from one random peer every 10 seconds. (Even if it made progress, just to add another potential source.)
