### ISSUE TITLE
Commit Many Execution Effects In A Single Pass For a Deploy

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1946]

**Comment by MParlikar** [comment]
From what I understand, this is an important optimization that should improve efficiency and throughput.  We should prioritize this @EdHastingsCasperLabs @piotr-dziubecki for 1.5

**Comment by dwerner** [comment]
@EdHastingsCasperLabs correct me if I'm missing the nuance here, but it appears to me that this issue is in an IS-A relationship (ie, duplicate of) https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1945 , which has a PR up https://github.com/casper-network/casper-node/pull/2277

**Comment by xcthulhu** [comment]
@dwerner this _might_ mean that we want to write all effects at once, rather than making many interstitial (and unreferenced) state roots as we write each effect at a time.

**Comment by dwerner** [comment]
@cspramit  this is distinct from https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/1945 , which has a PR up #2277 as I was asking about. So this should -not- be in review.
