### ISSUE TITLE
Reduce size of reactor event variants

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#1959]

**Comment by marc-casperlabs** [comment]
This needs benchmarking first and consideration of the alternative, which is simply boxing all events by default.

**Comment by marc-casperlabs** [comment]
## Message boxing

When we process messages, we shuffle them around from stack to heap and back, as they enter and exit the queue. More data copies may happen as they are passed around, wrapped, or unwrapped.

For this reason, it is a good idea to have fairly small messages. Large data should be boxed on the heap, which results in only the pointer (the `Box`) being copied.

### What are message sizes based on?

As our reactor messages (or component messages, which are wrapped by them) are `enum`s, they have a fixed size, which is based on the largest variant. For example, in the following code (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9919cb4b0518605a4717e4f40f046937)

```rust
struct Baz {
   a: u64,
   b: u64,
   c: u64,
}

enum NotBoxed {
    Foo(u8),
    Bar {
        data: u16
    },
    Baz(Baz),
}

enum Boxed {
    Foo(u8),
    Bar {
        data: u16
    },
    Baz(Box<Baz>),
}
```

the `NotBoxed` is typically 32 bytes in size, as it uses 8 bytes for the discriminant and 3x8 bytes for the `Baz` variant, while `Boxed` is only 16 bytes in size. Conversely, `Boxed` is half the size at 16 bytes, with additional memory being required to hold `Baz` on the heap. Note that this, in a large collection of `NotBoxed::Foo` values, would waste quite a bit of memory!

### How expensive are copies?

All reactor messages move frequently from stack to heap and back, as this happens every time they are put into a container (like a channel, queue or simple `Vec`) and retrieved from it. This is usually done what is commonly referred to as a `memcpy`, like the C function found in every libc (Rust can, due to its ownership semantics, usually guarantee that the memory regions do not overlap, which is a big deal). For example, `Vec::push` calls `copy_nonoverlapping`, which is a builtin, that on many platforms will call the actual `memcpy`.

So what is the typical cost of these copies? The most naive assumption is using a single byte-by-byte copy loop inside `memcpy`, which would mean it would take 64 steps to copy 64 bytes. However, most functions are optimized to be able to copy _at least_ the CPUs word size (8 bytes on 64 bit processors) at once, bringing it down to 8 steps. Good implementations should be able to take advantage of SIMD instructions, which can often copy as much as 32 bytes at once, thus bringing down the cost two 2 steps.

### What's our target and how do we get there?

This gives us a rough idea of a target size to shoot for - ideally, it would be <= 32 bytes, but that is hardly realistic, given that a single hash is already of this size. We could box every hash, but it would make collections of them rather unwieldy. 64, 96 and 128 are good targets as well though, while 256 seems quite large.

The task at hand is now to optimize the size of our main reactor's event. Currently, we use a few const asserts to ensure that some events do not grow beyond a certain point, e.g. a storage request:

```rust
const _STORAGE_REQUEST_SIZE: usize = mem::size_of::<StorageRequest>();
const_assert!(_STORAGE_REQUEST_SIZE < 89);
```

### Where are we now?

We would like to see something similar done for the `MainEvent`, which is the top level reactor event -- but it currently conspicuously absent. Here is where reality comes crashing in quickly though: At the time of this writing, the `MainEvent` is a gigantic 824 bytes on stable:

```rust
const _MAIN_EVENT_SIZE: usize = mem::size_of::<MainEvent>();
const_assert!(_MAIN_EVENT_SIZE == 824);
```

This is something that should be fixed, at a ceiling of 200,000 buffered events, that's up to almost a hundred megabytes of unnecessary memory usage just from event buffering, potentially more if queues get large. Also, the `Multiple` type alias (for a 2-item `SmallVec`) on `MainEvent` results on a type on the stack that is almost 1.7 KB in size.

### How to fix this?

First, to analyze type sizes and variants, a nightly compiler can be used with the following flags:

```sh
RUSTFLAGS=-Zprint-type-sizes cargo build > type-sizes.txt
```

This must be done on a nightly compiler (or using `+nightly`), and `cargo clean` should be run beforehand. We can see what the largest variants are:

```
[...]
print-type-size type: `casper_node::reactor::main_reactor::event::MainEvent`: 840 bytes, alignment: 8 bytes
print-type-size     discriminant: 8 bytes
print-type-size     variant `DeployGossiper`: 832 bytes
print-type-size         field `.0`: 832 bytes
print-type-size     variant `ApprovalsHashesFetcher`: 768 bytes
print-type-size         field `.0`: 768 bytes
[...]
```

It then becomes a matter of going down each variant and changing it to reduce size accordingly. This is not always a trivial task of taking a large type and boxing it, occasionally care should be taken to do a minor refactoring (e.g. when an `Arc` or something else is more appropriate). Additionally, it may be suboptimal to box-unbox and/or clone heap data needlessly, so each change should be looked at one a case-by-case basis.
