### ISSUE TITLE
Mainnet Replay Integration Test

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2007]
In order to optimize the contract runtime in a backward compatible manner, we need to replay blocks on mainnet as an integration test.

**Comment by piotr-dziubecki** [comment]
@dwerner could you provide the status update on this work?

**Comment by dwerner** [comment]
If I recall correctly, this is no longer possible (for the full length of history since genesis) because the auction changed to no longer use re-staking purses. This meant that at every switch block we produce a different hash from what we did before that change, and so re-executing blocks from before that change occurred results in a hash mismatch. What is possible is checking the hashes match since that change occurred. @xcthulhu

**Comment by RitaMAllenCA** [comment]
This is an older ticket and the comment above indicates it is no longer relevant.   @fizyk20 can you please confirm Dan's comment and close this out if it is no longer possible.  Thank you

**Comment by fizyk20** [comment]
If I understand correctly, this ticket was about benchmarking block execution times using data from a real network. If so, then as Dan said at the end - it is possible provided that we use recent enough blocks. I think the ticket still has merit and we might want to do that at some point.
