### ISSUE TITLE
Add JSON-RPC server tests - part 2

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2035]
This should cover both happy and sad path testing.

**Comment by rafal-ch** [comment]
Tests implemented as a part of: https://github.com/casper-network/casper-node/issues/1544

Whenever the `casper_client` library provides a corresponding function it is used to execute the test instead of a direct RPC call. The reason is that `casper_client` is the main "entry point" to the system and, in the first place, we should make sure it works correctly.

|RPC method|library call|happy|sad|comment|
|-|-|-|-|-|
|rpc_unknown_method|direct RPC|n/a|✓|**Sad path:** Sending correctly formed request with unknown RPC method|
|rpc_malformed_body|direct RPC|n/a|✓|**Sad path:** Sending the malformed request body|
|info_get_status|direct RPC|✓|✗|Sad path test is not applicable for this endpoint|
|get_state_root_hash|`casper_client::get-state-root-hash`|✓|✓|**Sad path:** Asking for a root hash before network reaches 1st era|
|account_put_deploy|`casper_client::put_deploy`|✓|✓|`put_deploy` and `get_deploy` are tested together in a single test named `account_put_deploy_get_deploy`<br /><br />**Sad Path:** Trying to put a deploy before network reaches 1st era|
|info_get_deploy|`casper_client::get_deploy`|✓|✓|**Sad Paths:** <br /><br />• Trying to get a deploy before network reaches 1st era<br /><br />• Trying to get a non-existing deploy|
|state_get_account_info|`casper_client::get_account_info`|✓|✓|Current test never sets the `maybe_block_id` parameter, hence the most recent one is used.<br /><br />**TODO:** a test case with non-default block_id is required<br /><br />**Sad Path:** Trying to get account info before network reaches 1st era|
|state_get_dictionary_item|||||
|query_global_state|||||
|info_get_peers|direct RPC|✓|✗||
|info_get_validator_changes|||||
|chain_get_block|||||
|chain_get_block_transfers|||||
|chain_get_state_root_hash|||||
|state_get_item|||||
|state_get_balance|||||
|chain_get_era_info_by_switch_block|||||
|state_get_auction_info|`casper_client::get_auction_info`|✓|✓|Current test never sets the `maybe_block_id` parameter, hence the most recent one is used.<br /><br />**TODO:** a test case with non-default block_id is required<br /><br />**Sad Path:** Trying to get auction info before network reaches 1st era|
|?|`casper_client::make_deploy`||||
|?|`casper_client::sign_deploy_file`||||
|?|`casper_client::send_deploy_file`||||
|?|`casper_client::transfer`||||
|?|`casper_client::make_transfer`||||
|?|`casper_client::get_block`||||
|?|`casper_client::get_block_transfers`||||
|?|`casper_client::get_item`||||
|?|`casper_client::get_balance`||||
|?|`casper_client::get_era_info_by_switch_block`||||
|?|`casper_client::query_global_state`||||
|?|`casper_client::list_rpcs`||||
|?|`casper_client::get_dictionary_item`||||
|?|`casper_client::get_validator_changes`||||

**Comment by rafal-ch** [comment]
Before continuing with the implementation of the next tests, I'm focusing on changing the `casper-test` engine to allow serial execution of checks. That will enable more seamless implementation of tests that interact with each other, like `put_deploy` and `get_deploy`.

**Comment by rafal-ch** [comment]
> Before continuing with the implementation of the next tests, I'm focusing on changing the `casper-test` engine to allow serial execution of checks. 

The above is now complete and waiting for review/merge.

**Comment by rafal-ch** [comment]
This ticket is now a mix of a few things:

1. Testing `casper_client` lib
a) Test of the `casper_client` that queries the node's RPC server
b) Test of the `casper_client` that do not query the node's RPC server
2. Testing direct calls to `RPC server`
3. Introducing sad path tests to the RPC calls (bypassing the `warp_json_rpc` crate)

@Fraser999 
I suggest splitting this ticket on the next grooming session (I'm happy to participate).

**Comment by rafal-ch** [comment]
The tests implemented as "Part 2" are now merged into `master`: https://github.com/casper-network/casper-test/pull/47
