### ISSUE TITLE
Make fast-sync work with `nctl`

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2070]
We want to test the following using something like the nctl upgrade tests:

* start a network using 1.4 binaries
* upgrade the network to binaries using fast-sync
* join a fresh fast-sync node using a post-upgrade trusted hash
* ~join a fresh 1.4 node after the upgrade (should sync to upgrade point then upgrade)~

**Comment by rafal-ch** [comment]
Note: `1.5.0` is built from `feat_fast_sync` branch with two cherry-picked commits from the following PR:
https://github.com/casper-network/casper-node/pull/2323/commits

Clearly, the update from `1.4.1` to `1.5.0` doesn't work:
```
Activation point: 4
starting node version 1.5.0
creating era supervisor
node panicking: current_era [era 4] <= chainspec.activation_era() [era 4]
```

Debugging of the upgrade process continues...

**Comment by rafal-ch** [comment]
The 1.5.0 node falls into the "Downgrade <-> Upgrade" loop:
```
starting node version 1.5.0
linear chain sync state: Syncing
run_fast_sync_task
joiner DowngradeVersion
starting node version 1.5.0
...
```
which, after ~250 cycles finishes with the panic mentioned in the comment above.

So, the `run_fast_sync_task` keeps returning `LinearChainSyncError::CurrentBlockHeaderHasOldVersion` until it finally returns the `Ok(block_header)`.

Checking what is the reason of `CurrentBlockHeaderHasOldVersion`...

**Comment by rafal-ch** [comment]
The sequence that causes the loop:

- `is_current_era()` is invoked
  - it calculates the diff between `Timestamp::now()` and `era_start` from `trusted_key_block_info`
    - the `trusted_key_block_info.era_start` is taken from `block_header.timestamp()`
    - and the `block_header.timestamp()` comes from storage (read block header with `block_height_index.iter().last()`)
  - the diff is compared against `chainspec.core_config.era_duration`

So, we calculate the diff:
```
2021-11-10T11:30:37.828Z - 2021-11-10T11:29:59.296Z = 38s 532ms, which is less than era duration (41s)
    current_timestamp                era_start
```
The above causes the `check_block_version()` to return `CurrentBlockHeaderHasOldVersion` and trigger the downgrade.

We repeat the above every few milliseconds, and finally we get:
```
2021-11-10T11:30:40.396Z - 2021-11-10T11:29:59.296Z = 41s 100ms (more than era duration)
    current_timestamp                era_start
```

At this point the `is_current_era()` returns `false`, so the `check_block_version()` doesn't return `CurrentBlockHeaderHasOldVersion` and the node stops requesting the downgrade.

**Comment by rafal-ch** [comment]
@afck 
With the changes we discussed (dirty-coded in this commit https://github.com/casper-network/casper-node/commit/8a0d88f176233771f31be83d0c666d70d18af498), after the upgrade to 1.5.0 the node again quits for a downgrade:
```
"INFO","fields":{"message":"restarting for downgrade","current_version":"1.5.0","old_version":"1.4.1"},"target":"casper_node::reactor::joiner"}
```
I'll continue the debugging and investigation on Monday (after the long-weekend).

**Comment by rafal-ch** [comment]
The logic behind node 1.5.0 restarting for downgrade:

In the `check_block_version` we have the following expression: `A && B && (C || D)`, where
* A: `is_current_era()` = true
* B: `header.protocol_version() < current_version` = true (1.4.1 < 1.5.0)
* C: `header.next_block_era_id() != chainspec.protocol_config.activation_point.era_id()` = false (era 4 != era 4)
* D: `header.is_switch_block()` = true

The result of the entire expression is `true`, so we return `LinearChainSyncError::CurrentBlockHeaderHasOldVersion` which triggers the "restarting for downgrade" in the joiner.

**Comment by afck** [comment]
Should D be `!header.is_switch_block()`? (Negation!) If I remember correctly, `(C || D)` was meant to prevent the downgrade unless C was a switch block _and_ right before the activation point?

**Comment by rafal-ch** [comment]
Testing process:
- Checkout the code from this branch `https://github.com/rafal-ch/casper-node/tree/2070_upgrade_1_4_to_fast_sync` - it is based on the `feat_fast_sync` + two cherry-picked fixes already made by @fizyk20 
  - Please bear in mind that it may be polluted with a lot of debug/tracing code
- set `RUST_LOG=trace`
- Run the helper script to start the upgrade test: `bash -i test_upgrade_rc.sh`
- Wait for the upgrade to 1.5.0 to start (script outputs: `STEP 5: upgrading network from stage (1)`)
- Check the running validators with `ps aux | grep -i validator`
  - initially, there will be "old" validators: `bin/1_4_1/`
  - check for the `... awaiting 2 eras + 1 block` output from the script
  - now, after awaiting is finished, you should see "new" validators: `bin/1_5_0/`
  - they will disappear quickly, and the script will not progress further (will be stuck at `... awaiting 2 eras + 1 block`)
- This is the time to inspect the logs from the nodes and see recurring `"restarting for downgrade"` messages
  - After ~260 repetitions, the upgrade/downgrade loop will finish and nodes will no longer run, reason:
```
{"timestamp":"Nov 16 17:43:52.746","level":"WARN","fields":{"message":"failed running \"/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-1/bin/1_5_0/casper-node\" \"validator\" \"/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-1/config/1_5_0/config.toml\"","exit_status":"signal: 6"},"target":"casper_node_launcher::utils"}
```

The final "crash" is **probably** caused by panic in `era_validator`. See here: https://github.com/casper-network/casper-node/issues/2070#issuecomment-964100457

**Comment by rafal-ch** [comment]
@afck @Fraser999 

Adding the negation to `!header.is_switch_block()` helped. Nodes don't restart for downgrade.

They, however, keep crashing later with:
```
panicked at 'Current era (EraId(4)) is before the last activation point (EraId(4)) - no eras would be instantiated!', node/src/components/consensus/era_supervisor.rs:164:13
```

I amended my last "wip" commit on the branch to include the negation.

**Comment by rafal-ch** [comment]
It seems we can reuse some code from the following PR: https://github.com/casper-network/casper-node/pull/2106

**Comment by rafal-ch** [comment]
Draft PR with a test: https://github.com/casper-network/casper-node/pull/2376

**Comment by rafal-ch** [comment]
Result of upgrading the `1.4.1` node to the `fast-sync` built from `https://github.com/afck/casper-node/tree/tmp_nctl_upgrade`, using also the launcher modified for the `fast-sync`:

- The test fails, due to some parsing not being correctly handled in bash:
```
2021-11-26T17:06:16.394188 [INFO] [276247] NCTL :: ... awaiting 2 eras + 1 block
parse error: Invalid numeric literal at line 1, column 8
bash: [: : integer expression expected
2021-11-26T17:07:37.577313 [INFO] [276247] NCTL :: ---------------------------------------------------------------------------------
2021-11-26T17:07:37.578397 [INFO] [276247] NCTL :: STEP 6: asserting node upgrades
2021-11-26T17:07:38.376390 [INFO] [276247] NCTL :: 3, 5
2021-11-26T17:07:38.377298 [INFO] [276247] NCTL :: ERROR :: protocol upgrade failure - >= 1 nodes have stopped
```
- the upgrade, however, seems to be successful
  - `stderr.log` remains empty
  - `stdout.log` shows `{"message":"handshake received","protocol_version":"1.5.0"}`
  - all nodes are up with status:
```
2021-11-26T17:14:31.375550 [INFO] [294208] NCTL :: node #5 :: status:
{
  "api_version": "1.5.0",
  "chainspec_name": "casper-net-1",
   ...
}
```

**Comment by rafal-ch** [comment]
Testing with the node based on the `nctl-upgrade` branch:
* Five nodes upgraded successfully
* Upgrade staged on node 6
* 6th node started as "fast-sync" (because launcher picks the most recent version)
* 6th node fails with: 
```
Error: No such switch block for upgrade era: era 3
Error: "/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-6/bin/1_5_0/casper-node" "validator" "/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-6/config/1_5_0/config.toml" exited with erro
```

**Comment by rafal-ch** [comment]
There is a need to change how the scripts for testing upgrade works. Currently, the launcher is downloaded **only once** and then used for the entire test. And the fast-sync nodes certainly need to be handled by the updated launcher.

Possible solutions:
* Make the test scripts always use the launcher from the local branch (to be agreed, since the backward compatibility of the launcher is required).
* Keep the launcher per staged node version (currently, there's a single launcher to handle all node versions)
