### ISSUE TITLE
Store the execution journal for step when there is an era end.

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2125]
once you complete 2124, regroup with principals to see if this is still needed.

**Comment by alsrdn** [comment]
Currently we don't store the execution journal for for step because the only way we report it is by converting it to a JSON  representation (called ExecutionEffect) and sending it out on the event stream server.
For this ticket we want to:
* change the event reported on the event stream to include the new json representation of the execution journal.
* figure out if/how the execution journal for step would be needed somewhere else that would require us to store it (e.g. a new RPC call).
  * If we do have a new use-case, store the journal and implement the required usage of it

**Comment by RitaMAllenCA** [comment]
Won't do: non-functional requirement, not currently necessary.   May consider doing it in the future.
