### ISSUE TITLE
Improve chainspec

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2154]
Make fields easier to understand and remove any than can be derived from others.

**Comment by afck** [comment]
E.g. instead of the `round_seigniorage_rate` we should specify the `annual_seigniorage`, which will be a human-readable percentage. The seigniorage per round or era can be computed from that.

The following probably need some discussion first:

* The unbonding delay could be specified approximately as duration (in hours/days) instead of number of eras.
* Instead of `minimum_round_exponent` we could specify the desired time between two blocks.

**Comment by devendran-m** [comment]
Won't do.
