### ISSUE TITLE
Test of the casper_client that queries the node's RPC server

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2231]
The scope of this ticket is to add tests within the `casper-test` framework that will cover both happy- and sad-path scenarios for the following `casper-client` library functions that rely on the RPC queries.

**Do not** test the RPC paths directly, rely on the calls to `casper-client` library.

The tests should focus on the correct schema being returned from the query, not on the actual returned data.

Please note that some test will be as straightforward as just calling a library function, while other may require quite an extensive setup. For example, to correctly test the `get_validator_changes` we actually need to setup a test network that will have a changes of validators between eras.

|`casper-client` lib query|corresponding RPC path|
|-|-|
|send_deploy_file|`/account_put_deploy`|
|transfer|`/account_put_deploy`|
|get_block|`/chain_get_block`|
|get_block_transfers|`/chain_get_block_transfers`|
|get_item|`/state_get_item`|
|get_balance|`/state_get_balance`|
|get_era_info_by_switch_block|`/chain_get_era_info_by_switch_block`|
|query_global_state|`/query_global_state`|
|list_rpcs|`/rpc.discover`|
|get_dictionary_item|`/state_get_dictionary_item`|
|get_validator_changes|`/info_get_validator_changes`|

***

**Additionally,** the following tests should be extended with a scenario that uses non-default (empty) `block_id`:

* casper_client::get_account_info
* casper_client::get_auction_info

***

Also, this PR makes changes to the `get_deploy()` and we should test it as well:
https://github.com/casper-network/casper-node-private/pull/28

**Comment by rafal-ch** [comment]
Progress tracking comment:

casper-client lib query | corresponding RPC path | happy path | sad path | comment |
-- | -- | -- | -- | --| 
send_deploy_file | /account_put_deploy |✓|✓|**Sad path:**<br /><br />• Try to send deploy to the network before it reaches `genesis`<br /><br />|
transfer | /account_put_deploy|✓|✓|**Sad path:**<br /><br />• Trying to make the transfer before the network reaches genesis|
get_block | /chain_get_block|✓|✓|**Sad path:**<br /><br />• Trying to make the transfer before the network reaches genesis<br /><br />**Todo:**<br /><br />• Add test when the block contains actual transfers and deploys|
get_block_transfers | /chain_get_block_transfers|✓|✓|**Sad path:**<br /><br />• Trying to make the transfer before the network reaches genesis<br /><br />**Todo:**<br /><br />• Add test when the block contains actual transfers|
get_item | /state_get_item| | | |
get_balance | /state_get_balance| ✓ | ✓ |**Sad path:**<br /><br />• Trying to get the balance of non-existing purse|
get_era_info_by_switch_block | /chain_get_era_info_by_switch_block|✓|✓|**Sad path:**<br /><br />• Trying to get the era info before the network reaches genesis<br /><br />**Todo:**<br /><br />• Technical debt: current implementation of `get_switch_block_for_era()` is vulnerable to race condition|
query_global_state | /query_global_state| ✓ |✓ |**Sad path:**<br /><br /> • Trying to get the global state with incorrect state root hash|
list_rpcs | /rpc.discover|✓|✗|No need to test for the sad-path, this call should always succeed|
get_dictionary_item | /state_get_dictionary_item| | | |
get_validator_changes | /info_get_validator_changes| | | |

**Comment by rafal-ch** [comment]
The wip PR with the tests mentioned in the comment above is here: https://github.com/casper-network/casper-test/pull/58.

Moving the ticket to `BackLog` because of other things taking higher priority (chunking + nctl vs fast-sync).

**Comment by rafal-ch** [comment]
~Getting back to the issue after several weeks. Some previously implemented RPC tests are failing, in some cases the reason is the discrepancy between actual and expected json response (probably due to the changes in the node made in the meantime), but some cases are unclear. I'm focusing on making all the tests green again.~

Update: all is running correctly when running against node from `dev`.

**Comment by rafal-ch** [comment]
Test for `send_deploy_file` completed.

**Comment by rafal-ch** [comment]
I'll request a few follow-up tickets to cover the "to be dones".

**Comment by rafal-ch** [comment]
Since this large PR still doesn't cover all the `casper client` functionality with tests, the following tickets are to be requested:

* Add test to check that node correctly responds with "I don't have such block" info - [#2632](https://github.com/casper-network/casper-node/issues/2632)
* Extend the `get_account_info` test to cover the case when provided `block_id` is not empty
* Extend the `get_auction_info` test to cover the case when provided `block_id` is not empty
* Improve the implementation of `pub async fn get_switch_block_for_era()` to prevent test flakiness, as described [here](https://github.com/casper-network/casper-test/pull/58#discussion_r817438431)
* Make the `checks` that query the `casper client` run only once (this requires prior merge of the convenience methods from [here](https://github.com/casper-network/casper-test/pull/65))
* Extend the `get_block` test to cover block with actual deploys and transfers
* Extend the `get_block_transfers` test to cover block with actual deploys and transfers
* Add test for `get_dictionary_item` that will actually put some items into the dictionary first
* Add test for `get_validator_changes` that will actually simulate the changes in the validator sets between eras
* Align all RPC tests to the `feat-fast-sync` branch - some of the RPC requests behave differently
* List and cover with tests all recently modified or added endpoints, for example, `info_get_chainspec`  added [here](https://github.com/casper-network/casper-node/pull/2703)

These tickets will also invalidate the [#2232](https://github.com/casper-network/casper-node/issues/2232), since the "non-querying" requests are actually needed to test the "querying" requests.

CC: @Fraser999 @piotr-dziubecki @marc-casperlabs
