### ISSUE TITLE
Add `write_bytes` method to ToBytes trait and implement for the most frequently used types.

### ISSUE THREAD

**Issue by goral09** [casper-network/casper-node#2412]
More tests revelead ~50% improvement when the non-allocating `ToBytes` alternative is implemented for `Trie` enum. 

Add `write_bytes(&self, writer: &mut Vec<u8>)` method to `ToBytes` trait. This method will not allocate intermidient vectors for serializing but will use `&self` and serialize to the `writer`. 

Default implementation of `write_bytes` should delegate to `self::to_bytes`.

Implement for most frequently used types.

**Comment by luis-casper** [comment]
I believe the method signature should be `write_bytes(&self, writer: &mut impl BytesWriter)`, where `BytesWriter` is a trait for memory or DB backends. Maybe `Fn(&[u8])` would do the trick too.
The reason is that the signature you propose would:
* Have to hold the entire serialized bytes in memory, when in reality we might just want to hold the DB buffer; and
* Either suffer from reallocations when the `Vec` grows or have to pre-allocate it, which would require caling `serialized_length()`, which we don't want to do for things like BTrees.

**Comment by goral09** [comment]
These are good points @luis-casper , thanks. As far as I know there's no such thing as _DB buffer_ and our API expect that data comes in as a `&[u8]` - meaning it has to be allocated somewhere. Which in turn requires that the `Vec` grew or was pre-allocated. 

Also, this is again, not a _final_ implementation of this approach but an intermediate step that improves the performance and is easy to integrate with existing code. There will be follow-up tickets next year that will let you (the EE team members) to think about the problem and come up with a better solution.

**Comment by mpapierski** [comment]
>. As far as I know there's no such thing as DB buffer 

https://docs.rs/lmdb/0.8.0/lmdb/struct.RwTransaction.html#method.reserve

Using it may be a bit tricky as we'd have to retain `serialized_length` but we should definitely try to see where it may fit

**Comment by goral09** [comment]
Nice find @mpapierski ! It looks like it does require that the size is known upfront - which will require calling `serialized_length()` as you say. 

You will definitely get a chance to implement it when we get a bit more time.

**Comment by luis-casper** [comment]
I see, LMDB requires the size to be known upfront!
