### ISSUE TITLE
Provide useful response in JSON RPCs where blocks or global state is missing due to fast-sync

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2632]

**Comment by rafal-ch** [comment]
Afaik, we cannot distinguish between these two scenarios:
* no such block, because it never existed (for example: random has was given)
* no such block, because the node being queried didn't download it (the block was not required for fast-sync)

hence, we cannot satisfy the "due to fast-sync" requirement.

**Comment by Fraser999** [comment]
We should be able to have storage keep track of the lowest block from which it has the complete unbroken chain of subsequent blocks (not just block headers).  This block height should be returned as part of the "no such block" and that alone should be enough to inform the caller as to the state of the node.

**Comment by rafal-ch** [comment]
OK, so for now in both scenarios we'll respond with something like `block not known, the earliest known block height is XXXX`.

**Comment by rafal-ch** [comment]
Keeping the exact in-memory representation on the blocks available in storage turned out to be problematic, mostly due to the fact that different blocks may share the same body and because in the fast-sync we might fetch them in different order.

This should be discussed before putting more implementation effort. We should agree on how precise the information returned in `lowest_contiguous_block_height` should be.

cc: @Fraser999 @afck
