### ISSUE TITLE
Include the protocol version in finality signatures. 

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2787]
6.2.23  Before doing this work, review the current 2.0 architecture for finality signatures and determine if this is still necessary. This is an old ticket and may be stale.  If it is no longer needed, please add a comment and close. 

  Include the protocol version in finality signatures.
Otherwise we'd double-sign after an emergency restart where blocks were rolled back

**Comment by xcthulhu** [comment]
Are we sure we need this for 1.5.1?

**Comment by afck** [comment]
I wasn't sure whether we are currently detecting double-signing in finality signatures anywhere. If we're not, it's less urgent. :+1:

**Comment by fizyk20** [comment]
I remember this being discussed, but I think we're not doing that yet.

**Comment by cspramit** [comment]
blocker is related ticket rather than blocked

**Comment by rafal-ch** [comment]
@Boiethios @fizyk20 @AlexanderLimonov 
please check if this is still needed?

**Comment by fizyk20** [comment]
It depends. If we ever want to punish nodes for signing two different blocks at the same height (which might be desirable), then we will need this.

**Comment by RitaMAllenCA** [comment]
6.21.23 standup: blockhash is part of blockheader.   since we sign the hash, we have an indirect direction to the protocol version so this is no longer needed.     
Double finality signatures: two potential blocks at same height; attempt to get more info; signature -->era --> signature set --> resolve which block is legitimate.  
Since we have a path, there is no value add to doing this.

**Comment by RitaMAllenCA** [comment]
necessary checks can be performed using the info in the block headers. Block is the source of truth and contains all info necessary.  No need to expose/propagate info any further out.
