### ISSUE TITLE
Triage replacing unwrap with result in runtime_args! macro. 

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#2808]
The macro runtime_args is heavily used but contains a potentially dangerous unwrap:
https://github.com/casper-network/casper-node/blob/18571e0c22d7918a953f497649b733151cfb3c3c/types/src/runtime_args.rs#L206

Requestor: Hans

**Comment by devendran-m** [comment]
```rust
#[macro_export]
macro_rules! runtime_args {
    () => ($crate::RuntimeArgs::new());
    ( $($key:expr => $value:expr,)+ ) => (runtime_args!($($key => $value),+));
    ( $($key:expr => $value:expr),* ) => {
        {
            let mut named_args = $crate::RuntimeArgs::new();
            $(
                named_args.insert($key, $value).unwrap();
            )*
            named_args
        }
    };
}
```

**Comment by devendran-m** [comment]
Ed says , this is due to the underlying usage of a Vec which is a general issue if a Vec any Vec allocate more memory it must panic. It's right at the edge of an OOM. The alternative is to use an implementation that is equivalent to a Vec but exposes a fallible try allocation. Unless Michal knows a better alternative, this is essentially a won't do.

**Comment by devendran-m** [comment]
Code paths that are concerned about this, the macro isn't required and can be replaced with direct allocation of inserting in that logic. Therefore, closing as won't do as per the triage on 2nd Oct.
