### ISSUE TITLE
Revert breaking API changes in casper-ee

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#3072]

**Comment by georgepisaltu** [comment]
After analyzing all the changes in `casper-execution-engine`, the following breaking changes were found:
- removal of `DEFAULT_MAX_DELEGATOR_SIZE_LIMIT`
- removal of `DEFAULT_MAX_STORED_VALUE_SIZE`
- changes and renames in the `storage::Error` hierarchy (result of the LMDB -> rocksdb migration)
- removal of `max_delegator_size_limit`
- removal of `max_stored_value_size`
- removal of the `Runtime` traits and subsequently moving most of the methods to the `Runtime` struct itself
- introduction of `TrieOrChunkedId`
- introduction of `ChainspecRegistry`

After inspecting the relevant code and trying to make these changes backwards compatible, I found there is no feasible way to do this because it would mean reverting most of the functionality added since the last release, which defeats the point.

The core of this issue is that the execution engine API is too permissive as of right now, publicly exporting most of its modules, where the `struct`s and `fn`s are mostly public as well. At some point we should refactor the API to only expose the relevant endpoints. This will allow us to restrict the set of user-facing changes when we consider releasing a new version and also allow more flexibility for changes under the hood. Because of the graph-like dependencies inside the execution engine and the fact that most things are public in the API, almost any change would be a breaking one.

For now, in order to respect `semver` standards, we must release a major version of `casper-execution-engine`.

The PR for this issue will add `non-exhaustive` to error enums and also restore `write_scratch_to_db` in a deprecated state (replaced by `write_scratch_to_lmdb` as part of the DB migration).
