### ISSUE TITLE
 Add the option for specifying upgrade era ID in validator updates in global-state-update-gen

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3303]
Currently, when generating updates to the validators set, the tool reads a snapshot from the state of the auction contract, and then generates a new snapshot for the same eras. But that means that in order for the snapshot to include the correct eras after the upgrade, the base snapshot must come from the last block before the upgrade - which is inconvenient, as it precludes preparing such updates in advance. To improve UX, an option should be added to specify the era ID at which the upgrade is supposed to happen, so that the snapshot can be generated for the eras starting at that ID regardless of which eras were included in the base snapshot.

**Comment by RitaMAllenCA** [comment]
4.7.23 grooming discussion: no one recalls the objective of this request as written.   @fizyk20 @thamps-casp if you can update the text to be more specific to the use case, please do.  Otherwise close the issue if it is no longer relevant.

**Comment by fizyk20** [comment]
The idea here is: say that we want to do generate a `global_state.toml` file for an upgrade at era `N`. Currently, the only option to do that is to use the state root hash from the switch block of era `N-1`. But that might be inconvenient, as it means we must either hard-reset the network to era `N` at the upgrade, or stop it after era `N-1` ends and restart it once the upgrade has been prepared. It is impossible to stage an upgrade for era `N` in advance on a running network.

Thus, in order to support such a use case (which is mostly relevant to private networks in which an upgrade with global state twiddling is the only way to rotate validators), it would be useful to be able to tell the `global-state-update-gen` tool something like "I want to use this global state from era X, please generate a file that would work with an upgrade at era Y (that is not X+1)".

**Comment by devendran-m** [comment]
Not important to do it currently, therefore closing.
