### ISSUE TITLE
Missing Metrics on joiner nodes to be investigated from RC tests

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3485]
missing metrics on joiner nodes
current_era - always 0
amount_of_blocks - finalised block count 0
finalization_time - block finalisation time

**Comment by alsrdn** [comment]
The metrics are missing on joiner nodes because these are actually consensus metrics. If the joiner are not validating than these metrics wouldn't increment.
Indeed the metric names are a little bit confusing. My proposal is:
* For `amount_of_blocks` and `finalization_time` I don't think we should change anything since they are working as expected.
* For `current_era`:
  - we can add another metric called `consensus_current_era` to track what `current_era` is actually tracking right now
  - change `current_era` to track the era of the latest synchronized block in case the joiner is in `KeepUp/CatchUp`.

**Comment by rafal-ch** [comment]
The decision is to rename "current_era" to "consensus_current_era". Other metrics should stay as is because they could be easily connected to consensus by just the name.
