### ISSUE TITLE
Node stuck and cannot participate (1/8 joiners have not yet joined after 5+ hours)

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#3504]
Detailed description here: https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1671003062388689

TODO:

- make sure we're not overeager with banning
- SRE: use refreshed trusted hash
- verify restart frequency vs blocklist duration (10 min.?) - no sense in restarting while banned
- check the logs of the other nodes to see if they banned the "stuck" node

**Comment by alsrdn** [comment]
The reason why this node is not joining is because the trusted hash that it's using to sync eventually becomes stale. Because the node is being restarted with the old trusted hash, it keeps trying to sync, gets rejected sync leaps and stops. It then gets restarted and repeats this behaviour indefinitely.

In order to prevent this from happening, when the node gets restarted, we should provide it with a different, newer trusted hash.

The TL;DR is that:
* Node attempts to leap multiple times when first started
* It takes a while to get the global state but the metrics show that it's progressing to download
* The node keeps leaping until at one point it failed to leap since the sync leap requests time out
* At this point the node shuts down which is normal behaviour
* Node does not appear to be banned when this happens and node does seem to have sufficient fully connected peers
* Node restarts a few times until the trusted hash becomes too old, sync leap is progressing in this case, global state is being downloaded.
* Other joiner nodes in this setup get restarted as well but manage to catch up before the trusted hash becomes too old.

**Comment by cspramit** [comment]
Aj confirms testing with latest trusted hash
