### ISSUE TITLE
Large network upgrade test: network stalled

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3597]
Network: 100 + 20
Branch: dev
Chain: public
Commit: ea7d7b2b6377df20b755315652b4584f006d85d8
Config Override: '{"config":{}, "chainspec":{"era_duration": \"1h\"}}'
Upgrade Testing 1.50 (ea7d7b2b6377df20b755315652b4584f006d85d8 -> 1.5.0 (ea7d7b2b6377df20b755315652b4584f006d85d8
**Result: Failed, Network Stalled**
Observations:

**- All validating nodes switched to 'KeepUp' before upgrade activation at Era 2

- No blocks created**

Dumps: http://genesis.casperlabs.io/rti-dev-big/casper-node-dumps/rti-dev-big/23012023_0024/dump_download_list.txt

**Comment by fizyk20** [comment]
This is likely related to changes in `refresh_contract_runtime`. The way this function currently works and how we're calling it, it sometimes sets the state of contract runtime back instead of updating it. I will modify the logic so that it's only called after a new block is made complete and its height is greater than or equal to the next block expected to be executed by contract runtime.

This issue is also likely what blocks my other work on #3573 .
