### ISSUE TITLE
Big network node stop-start test issue with , syncing speed and network stalled

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3598]
Issue: Nodes were stopped and restarted(after 10 blocks) with no load in one test instance and light load( mixed deploys over 15 min) in another test instance.

- historical sync slow in both cases with downloading each block taking upto 30 sec (even empty blocks)

- In the case of test with light load additionally the historical sync stalled and did not progress beyond  block 320
**Details below**

Network: 100 + 20
Branch: dev
Chain: public
Commit: ea7d7b2b6377df20b755315652b4584f006d85d8
Config Override: '{"config":{}, "chainspec":{"era_duration": \"1h\"}}'
Node Testing for Sync Performance
**Test1:** random node stop - delay 10+ blocks - start with no load
Observations:

- single validating or single non-validating nodes startup successfully

- showing upto ~30s to historical download 1 empty block ?
- Historical sync Block 78 -> 61 (node shutdown point)
- 1:58:20 -> 02:05:40 = ~2mins / 10 blocks
**Test2:** random note stop - delay 10+ block - start with light load
Observations:
- non-validating node running in KeepUp (but historical sync and CatchUp is quite slow)
- sending mixed load (25 x delegations, 50 x mints, 5 x large wasms)
showing slow block sync
- Historical sync Block 342 -> 118 (node shutdown point)
- **historical sync stalled and not progressing beyond block 320**
Grafana: https://grafana.casperlabs.io/goto/jcnux1oVz?orgId=1
Dumps: http://genesis.casperlabs.io/rti-dev-big/casper-node-dumps/rti-dev-big/23012023_0743/dump_download_list.txt
Node of Interest: 172.142.98.149 (non-validating)

**Comment by cspramit** [comment]
https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1674461300292789

**Comment by rafal-ch** [comment]
Original test: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1674461300292789
SyncLeap loop

Re-run: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1675046440956279
different issue surfaced (forward sync - not enough finality)
this is ticketed to be fixed in https://github.com/casper-network/casper-node/issues/3612

Re-run: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1675150973415159
Works ok, but with no load.

@thamps-casp 
~Please repeat the "original test" (i.e. "test2", include the load).~
Test has been re-run, all attempts to re-join a node were successful: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1675393031576859 (**Test2**)
