### ISSUE TITLE
Mainnet snapshot + Joiner with load issue

### ISSUE THREAD

**Issue by cspramit** [casper-network/casper-node#3723]
Network: 5 + 2
Name: ajith-mainnet-clone
Mainnet Bootstrap + Joining Node
Branch: PR#3708
Commit: a565f9e1497deeadca8eb331b027b8c7f76dcf44
Tests: Emergency Upgrade and Light to Moderate Load
Observations:
1st flight - light deploys of ~2000 deploys every 5 mins
network shows slight degradation with continous load
2nd flight - medium load of ~5000 deploys every 5 mins
**network degradation was sooner and eventually stalled**
**majority validating nodes transitioned to 'CatchUp'**
**deploys not executing quickly enough**
build of deploys in the buffer probable cause ?
load of ~5000 deploys of native and wasm transfers per 5 mins continous
Dumps: http://genesis.casperlabs.io/ajith-mainnet-clone-3/casper-node-dumps/ajith-mainnet-clone-3/02032023_0309/dump_download_list.html
https://grafana.casperlabs.io/goto/3U6wC-xVk?orgId=1

**Comment by rafal-ch** [comment]
@cspramit @thamps-casp 
can you re-run this scenario?

**Comment by thamps-casp** [comment]
Running the test with latest `dev` commit - `8516bac904c6d0cad14a725eca723e704fcb877a`

Observations:
1st flight - light deploys of ~2000 deploys every 5 mins
network shows slight degradation with continous load. But network progressing

2nd flight - medium load of ~5000 deploys every 5 mins
network not showing any degradation and network progressing

On investigating:
- block finalisation times are around ~22secs and normal on all nodes
- block is generated every 32s as per SSE
- when `light` load is sent, block create interval shows slight increase for some reason
  - block time shows upto 50s to create next block (refer Block Round Times on grafana)
- with `medium` load, not observing any block create interval time change

Light Load:
This is as sending "100 deploys x 3 parallel threads" 6 times every 5mins ie, 300 transfer deploys are sent to the node. 

Is the Deploy Acceptor slowing down when a bulk of deploys sent to it in a second?
OR 
Is metrics engine somehow impacted because of deploys acceptors and showing as delay on grafana?

![image](https://user-images.githubusercontent.com/74213253/225521124-259b45b1-1df6-4e55-b4b3-c2190bd13280.png)

![image](https://user-images.githubusercontent.com/74213253/225521197-a19d76b1-34df-4274-a8ca-f0acc4a6ba06.png)

Dumps1: http://genesis.casperlabs.io/ajith-mainnet-clone-3/casper-node-dumps/ajith-mainnet-clone-3/16032023_0034/dump_download_list.html ( 1st flight of light load)

Dumps2: http://genesis.casperlabs.io/ajith-mainnet-clone-3/casper-node-dumps/ajith-mainnet-clone-3/16032023_0325/dump_download_list.html ( 2nd flight and re-run with medium loads)

**Comment by rafal-ch** [comment]
I'm closing this issue as we observe that none of the nodes have ever switch back to `CatchUp` during the course of the test above. We'll track the slow network progress in a separate issue.

**Comment by Fraser999** [comment]
@thamps-casp I had a look through the logs and it looks like both tests are exhibiting similar behaviour: namely, the actual block timestamps are unaffected (regular 32 second intervals) but when a batch of deploys hits the network, completion of execution is delayed a bit.  I'm not sure where the grafana Block Round Times metric is derived, but the delay in completing execution would manifest in e.g. a delay in reporting the block executed in the event stream.
