### ISSUE TITLE
Node doesn't mark a forward block complete and is stuck when there's a delay caused by I/O

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3748]
Node fails to progress due to the following chain of events:
high disk load -> even queue clog -> long block execution time -> premature purge of acceptors -> mark complete request ignored (not enough finality due to missing acceptor)
Current flow:
- contract runtime executed the block given by consensus and announces meta block
- meta block handler notifies other components (sends to deploy buffer, updates validator matrix, update meta block gossip state, sign the block, store and broadcast the signature) and kick-start the block accumulator
- block accumulator is getting sigs, but it relies on gossiping and broadcast only (no active fetch of signatures)
- if block accumulator can't get enough sigs (strict), block will never be marked complete (and node is stuck)

Proposed solution:
- consensus produces a finalized block
- we send it to block synchornizer (we could short circuit into HaveBlockHeader state)
- synchronizer is supposed to get all sigs, execute block and mark it complete
- currently this may get stuck (chicken & egg problem with first signature vs execution)
- need to change the flow to recognize if this is "our" block and execute it first and broadcast the sig

Alternative solution:
- contract runtime executed the block given by consensus and announces meta block
- meta block handler notifies other components (sends to deploy buffer, updates validator matrix), update meta block gossip state, sign the block, store and broadcast the signature and kick-start both the block accumulator and the block synchronizer (we can short circuit and go directly into HaveAllDeploys - should be ok even for empty block)
- meta block.executed should be set to true
- synchronizer actively fetches the missing signatures (until it has Strict) and then marks the block complete
- (at the same time) accumulator listens for broadcasted signatures (accumulator will be eventually purged)
- accumulator should no longer mark the blocks complete

Third proposed solution: keeping the whole thing as is with minor tweaks:

- when it's a consensus block, we have a flag in the accumulator for it to make the distinction
- we mark them complete as soon as we sign them (as it's consensus stuff so we have a high degree of confidence there)
- in the accumulator we send it with this special flag
- it sits in the accumulator for as long as it needs to gather the sigs
- when the required amount of sigs is there, we purge the acceptor (block is already complete)
- 

As a first part of this task we should create a test that reproduces the issue and then make it green by implementing the solution.

**Comment by georgepisaltu** [comment]
Third proposed solution: keeping the whole thing as is with minor tweaks:
- when it's a consensus block, we have a flag in the accumulator for it to make the distinction
- we mark them complete as soon as we sign them (as it's consensus stuff so we have a high degree of confidence there)
- in the accumulator we send it with this special flag
- it sits in the accumulator for as long as it needs to gather the sigs
- when the required amount of sigs is there, we purge the acceptor (block is already complete)

**Comment by rafal-ch** [comment]
solution is to be discussed

**Comment by rafal-ch** [comment]
Suggestion:

**solution not ready yet**

Current flow:
* when in `Validate` node produces a "finalized block"
* ContractRuntime executes this block announces "Block executed" (we notify accumulator)
* we sign the block 

Updates:
* create synchronizer (forward builder) with block hash (put it in HaveAllDeploys state, execution state = done)
* synchronizer will grab the "our" sig from storage and will try to fetch strict finality from peers and switch to HaveStrictFinality
* if we're in Validate, we add a new "special" flow

New flow:
* if forward builder is finished, control logic marks it complete
* 


* notify the accumulator and synchronizer (forward sync flow, because we want to execute the block)
* synchronizer will handle enqueueing to contract runtime
* **the problem:** synchronizer will do it only after it gets strict finality (TODO)
* block synchronizer will try to acquire signatures via fetch
* in the meantime we might still be getting gossiped signatures via accumulator (this is fine)

* (new queue needed - block for synchronization, implementation details to be agreed, could be a vec of synchronizers or linear chain component, etc.)
