### ISSUE TITLE
Failing upgrade test: Missing finality signatures, sync back stalled

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3757]
The upgrade test fails on CI here: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/7769/2/4
The reason is that the sync back process is stalled on trying to get finality signatures for block 119. Even though the symptoms are identical to the one from the [#3747](https://github.com/casper-network/casper-node/issues/3747), we think the root cause is different, i.e. in the NCTL based network we expect all peers to be fully saturated with signatures, so they should never return Absent error.

**Comment by Fraser999** [comment]
It turns out that this does boil down to the same issue as for #3747.

In the test, nodes 1-5 are the genesis nodes, the network is upgraded, then nodes 6-10 are bid in but not started for a couple of eras, and finally started.

Nodes 1-5 stake way more than nodes 6-10, so the upgraded network continues to run for the period of time where 6-10 are deemed validators but are not running.

Once nodes 6-10 are started, they are joining mid way through an era in which they are validators.  They all correctly receive sync leaps and attempt to sync the initial block - a block which they would have signed if they had been validating at the time.

Node 6 does manage to completely sync this block and transition to Validate mode.  However nodes 7-10 all fail in the same way: when trying to acquire strict finality signatures, they keep requesting the same 5 signatures - the signatures of nodes 6-10.  Since these signatures were never created and will never be created, they are trapped in this state.

The fix seems to be the same as discussed for #3747, i.e. randomise the list of validators from which we choose 5 to fetch.  This would have undoubtedly allowed nodes 7-10 to complete the sync of that block and transition to Validate mode.

As such, I'm closing this ticket as a duplicate.
