### ISSUE TITLE
merge feat-private-chain (aka private-1.4.8) into to dev

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3944]

**Comment by RitaMAllenCA** [comment]
@mpapierski please do this asap

**Comment by mpapierski** [comment]
As discussed on standup today with @EdHastingsCasperLabs, here are steps to follow:

- I'll first merge the `feat-private-chain` branch (private-1.4.8) to dev since 1.5.x is already released, so all the private chain functionality is in the main code as part of this ticket
- ~~I'll wait for information from @sacherjj regarding the upgrade path for a private chain, from what we currently know that likely means merging: v1.4.9 into feat-private-chain, v1.4.13 into feat-private-chain, v1.4.14 into feat-private-chain, v1.4.15 into feat-private-chain, then v1.5.1 into feat-private-chain, and once that's done they'll be able to use mainline release.~~
- Need to verify tip pruning occurs as released with 1.4.15.
