### ISSUE TITLE
Investigate the nightly test failure - upgrade_after_emergency_upgrade_test.sh

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3964]
This test has been observed to fail rarely with restart count mismatch. Logs and network dump attached. Tested on commit: 7eaf00a20e96b729262d8da0b0ad709bfae82584
[net-1.zip](https://github.com/casper-network/casper-node/files/11488736/net-1.zip)
[net-1.log](https://github.com/casper-network/casper-node/files/11488737/net-1.log)

**Comment by fizyk20** [comment]
The issue is due to one node not going through the second upgrade, because it is waiting until it finishes gossiping enough finality signatures. However, it cannot finish doing so, because all the other nodes have already upgraded and are rejecting connection attempts because of protocol version mismatch.

This is generally expected behavior, but we will add a timeout to the `ShutdownForUpgrade` state, so that if a node is in such a situation, it will eventually proceed through the upgrade, anyway.
