### ISSUE TITLE
non-backwards compatible change in the nodes 1.5.0

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#3996]
It seems that there is a non-backwards compatible change in the nodes 1.5.0 build version. When connecting sidecar to testnet we sometimes get a message that the enum defined in casper-types 2.0.0 . AFAICT the issue is with Transform enum. [Currently](https://github.com/casper-network/casper-node/blob/release-1.4.15/types/src/execution_result.rs#L446) there is no WriteUnbonding enum branch, but [1.5.0-rc](https://github.com/casper-network/casper-node/blob/release-1.5.0-rc.1/types/src/execution_result.rs#L97) does have that. Should we be introducing a non-backwards compatible change in a minor version change?

**Comment by zajko** [comment]
Just a clarification - when I was writing on slack I wrote that this was observed on testnet, when in fact it was an integration tests node.

**Comment by Fraser999** [comment]
Unfortunately we don't currently follow semver rules in the `casper-node` crate.

While we do aim to follow semver rules for all the other crates in this repo, we instead keep the `casper-node` crate version in sync with the Mainnet protocol version.  The intention is that as of node 2.0, we'll move away from this, allowing the protocol version (which will hopefully become a single integer rather than a semver) to increment at a different pace to the crate's version.

Also for node 2.0, we plan to further reduce the need for external projects to depend upon the `casper-node` crate by moving the remaining shared types (e.g. `Block`, `Deploy`, `Chainspec`) out into the `casper-types` crate.
