### ISSUE TITLE
Use runtime::print in panic handler when test-support and debug is enabled

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4002]
Use runtime::print in panic handler when test-support and debug is enabled
Description: Debugging smart contracts is probably the most difficult when you hit Unreachable trap: could be panic, could be max stack height limit, abort, overflow, unwrap, etc. By adding a runtime::print to a panic handler we can print the actual error message that’s happening inside wasm. This will make people lives easier.

**Comment by rafal-ch** [comment]
@mpapierski 
The [simple approach](https://github.com/rafal-ch/casper-node/commit/8d15ca62019d647dd3874bb8bb761852a310c379) resulted in **15%** increased gas cost:

As reported by `host_function_metrics_has_acceptable_gas_cost` test:
```
before gas cost = 347080271020
after gas cost  = 399500059000
```

This is most likely caused by the allocation needed to create the appropriate message from the `PanicInfo`, because printing a static string increases the gas cost only by 0,12%.

I'm currently checking some other methods to get the proper message, but all result in severely increased gas cost:
* `_info.payload().downcast_ref::<&str>()`
* `_info.to_string()`
* `_info.message()` <- experimental, nightly only API

I'll check some more options, maybe we can use `file: &'a str,` and `line: u32,` from `Location`.

**Comment by rafal-ch** [comment]
A replacement [PR](https://github.com/casper-network/casper-node/pull/4229) is ready to review.
I'm unable to link it to the issue.
