### ISSUE TITLE
Add a ChainspecReport to immediate switch blocks

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4036]
Immediate switch blocks should contain the chainspec settings that are relevant to the part of the chain in that protocol version, for the chain to be self-descriptive.

This is NOT the entire chainspec - only the specific pieces needed to validate blocks as part of the lookback portion and/or validate historical blocks.   lookahead/lookback is problematic for the sync-back otherwise. 

work with @fizyk20 to determine which fields need to be included.   Then work with @rafal to identify them in the chainspec so they can be added to immediate switch blocks.

**Comment by EdHastingsCasperAssociation** [comment]
Why is this assigned to me?

**Comment by fizyk20** [comment]
It is unclear to me if this is still needed. It was definitely needed in the initial design of finality signature rewards, as then we had no way of telling which block the `rewarded_signatures` field refers to (as there was a single bitmask referring to a single block `n` blocks in the past, for an unknown `n`), but in the modified ("window") design, it is clear without any additional info (now we have a vector of bitmasks corresponding to `n` blocks starting with the parent one - but `n` is now known, it is the length of the vector).

The only use of this addition would now be for block validation, but we don't need it for validating new blocks (as we can do that based on the chainspec itself), and we don't need to validate historical blocks at all, other than checking if they match their hash. So this doesn't seem to be useful at all.

Also, if we decide to do it anyway, maybe it would be a good idea to store the relevant information in the global state, instead of in the immediate switch block? It would then be accessible from any block, not just from the immediate switch block.

cc @EdHastingsCasperLabs @Boiethios
