### ISSUE TITLE
Create Extensibility PoC

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4056]
In this PoC we'll provide extensibility to: Digest, BlockHeader, StoredValue and [BlockBody](https://github.com/casper-network/casper-node/pull/4004)

- must still be able to deserialize new struct from old bytes
- if type already has a tag (ex: enums, option) - use the tag to continue the extension!
`struct Block {}`
-into-
`enum Block {
    BlockV1(inner),
    BlockV2(inner),
}`
- All public types? Is it part of the ABI? yes --> extensible; no --> Should it be? yes --> make it so and make it extensible if necessary; no --> standardize serialization to bytesrepr if needed; otherwise done. 

- [ ] Digest:
- we have:
`pub struct Digest([u8; Digest::LENGTH]);
`
- we want:
`pub struct Digest([u8; 64]);
`-or-
`pub struct Digest(Vec<u8>);
`

- [ ] BlockHeader

```
struct BlockHeader {
    - current fields -
    approvals_hash: Vec<ApprovalsHash>,
}

```
```
pub struct DeployHeader {
    // remove `dependencies: Vec<DeployHash>`
}
```

- [ ] Extend Stored Value
- add `Account(Account)`
-or-
- add `AccountV2(AccountV2)`

**Comment by RitaMAllenCA** [comment]
the PoC is being built around the BlockBody struct and the past_finality_signatures field, because this is what is already being implemented by the "Zug rewards" team.
the outcome should be a PoC ready for review + a doc (CEP?) explaining our approach

**Comment by rafal-ch** [comment]
@RitaMAllenCA 
The PoC code is available here (as compared to `feat-2.0`):
https://github.com/casper-network/casper-node/compare/feat-2.0...rafal-ch:casper-node:feat-data-extensibility?expand=1

This PoC covers the extended `BlockBody` to allow storing `past_finality_signatures` required by the Zug rewards work.

Since I want to avoid developing a feature on my own for too long, I propose that next changes to the `feat-data-extensibility` branch should be added by regular PR/review process. Therefore, I'll put the issue to "In review".

**Comment by rafal-ch** [comment]
Below is a description of the idea behind the approach we've taken.

[data_extensibility.md](https://github.com/casper-network/casper-node/files/11914966/data_extensibility.md)

**Comment by rafal-ch** [comment]
@RitaMAllenCA 
Closing as the PoC is done, further work is to be done with dedicated tickets.
