### ISSUE TITLE
Investigate the failure of `bond_its.sh` test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4070]
This [test failed](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8525/1/4) in one of the nightly test round (single observation). Validator was evicted, but it's been proposing even after an "auction delay". It is worth checking if all the assertions in the tests are written correctly.

**Comment by alsrdn** [comment]
The test failed because node 6 was stuck and could not transition to `KeepUp` after it was done validating.
After the node was unbonded, it should have stopped being a validator from era 9. The node detected correctly that it should not be a validator starting with era 9 and attempted to transition from `Validate` to `KeepUp`.
When trying to transition the node attempted to deactivate era 8 which failed because era 8 was already deactivated when the last block of the era was added. This led to a fatal error but since the node is still in `Validate` mode and we don't allow the node to shut down in this state, it remained stuck.
