### ISSUE TITLE
Investigate stuck historical sync on large network test

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4077]
Investigate stuck historical sync issue reported here: https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1687350784393109

**Comment by rafal-ch** [comment]
There is an infinite sync leap loop due to missing info about validators for era 0:

Chain of events:
1. Node is syncing back through Era 0 (going towards genesis of the pre 1.5 chain)
2. Validator matrix is correctly saturated
3. Node hits activation point and restarts for upgrade
4. Upgraded node starts and resumes historical sync
5. It attempts a leap with `trusted_ancestor_only = true`
6. Sync leap comes back with `trusted_ancestor_headers` being empty (as there is no switch blocks before the trusted block header)
7. Node can't get validators for era 0
8. Goto 5

**Comment by rafal-ch** [comment]
The proposed solution:

If the `trusted_ancestor_only = true`, but we ask for a block in Era 0, fill the `signed_block_headers` with a single block (switch block of Era 0).

When such sync leap response arrives, it is expected that node will register validators for era 1 (and, by inference) for era 0, and will be able to continue the sync process.

**Comment by rafal-ch** [comment]
@Boiethios please work on the test that reproduces the issue, unless some more priority tickets regarding 2.0 rewards appear.

NCTL test might be tricky to create, because it's hard to kill the node at the exact moment. Maybe we can extend the `diagnostics port` functionality?

**Comment by alsrdn** [comment]
A summary of the work done so far for this issue:
* Modify sync leap to include the switch block of era 1 if the sync leap request is coming for a block in era 0: https://github.com/casper-network/casper-node/pull/4081
* Read the validators for era 1 from global state as they are automatically inferred for era 0 if the validators for era 0 are missing for the matrix: https://github.com/casper-network/casper-node/pull/4116
* Request a sync leap for the switch block in era 1 if the highest orphaned block is in era 0 and the validator matrix does not contain the weights for that era: https://github.com/casper-network/casper-node/pull/4129

All above PRs address the issue but there have been a couple of corner cases discussed in the PRs:
* what happens if the highest orphaned block is the first block of era 1 and we don't have the parent header (the header for the switch block in era 0)?
* what happens if the highest orphaned block is the first block of era 1 but this block is also a switch block (e.g. if the era length is 1 block)?

Next steps:
* Attempt to write an automated test for validating the fixes for this issue and try to cover the corner cases in the test
