### ISSUE TITLE
Investigate nodes missing their turns to propose in an idle NCTL network

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4090]
We're seeing the leader missed their turn messages in fresh NCTL networks under no load. Under such conditions, there should be no reason for nodes to be missing their turns for proposing blocks, so this might be indicative of some deeper issue.

**Comment by RitaMAllenCA** [comment]
@fizyk20 @Boiethios estimate?

**Comment by RitaMAllenCA** [comment]
6.29.23 - this was recreated on a faster storage setup so we will investigate for next release.

**Comment by fizyk20** [comment]
Findings:
The issue seems to be caused mainly by the 2 seconds default delay between reactor cranks in `Validate` mode ([relevant code](https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/main_reactor/validate.rs#L19)). Since 2 seconds is half of a consensus round in NCTL tests, this delay will often cause nodes to miss the planned time of the start of a new era, thus causing a missed proposal.
On machines with slower (ie. non-SSD) storage, this is further compounded by storage slowness.
The code path initializing a new era could be modified to bypass the crank delay, but such a modification might not be worth it at this point, so I'm closing the issue for now.
