### ISSUE TITLE
Fix network stall where all validator nodes switch to CatchUp

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4091]
In a [recent run](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8548) of the network_soundness.py test we discovered that the network stalled because all validator nodes switched to CatchUp and remained in that state without recovering and switching to KeepUp and then to Validate. More details [here](https://casper-labs-team.slack.com/archives/C01R7C1FV8F/p1687791167931339?thread_ts=1687431289.486619&cid=C01R7C1FV8F)
While the root cause that brought all the nodes to CatchUp seems to be that no blocks were finalized during the dead_air_interval, the nodes should have recovered back to Validate eventually. From a quick look it seems that there is a corner case where the sync leap response is never checked. In this ticket we want to:
create a more reliable test where we can see that the network stalls when all validators switch to CatchUp
attempt a fix that allows the node to recover back to Validate mode

**Comment by RitaMAllenCA** [comment]
possible solutions: 1 - periodically switch out of catchup or 2- incorporate sync leap in validator logic rather than switching to catchup.    Root cause: some nodes get stuck due to the majority of validator weight leaving and they don't come back if enough validator weight comes back on.  Will schedule for next release
@EdHastingsCasperLabs WDYT?

**Comment by alsrdn** [comment]
Pending discussion

**Comment by alsrdn** [comment]
Added test in this PR: https://github.com/casper-network/casper-node/pull/4120

**Comment by alsrdn** [comment]
This issue appeared only on the `dev` branch after we merged https://github.com/casper-network/casper-node/pull/4042.
The reason why the issue did not surface with the previous version of the code was that we had a stall detection in place that purged the historical builder of the block synchronizer after some time of inactivity passed. This led the node to detect that it has caught up and switch state to KeepUp and then repeat this process.

Since we removed the stall detection in the mentioned PR because we had a better solution for fixing the latching issue, the node would not switch out of CatchUp anymore.
