### ISSUE TITLE
Investigate slow historical sync in 1.5.2 testnet

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4215]
per title

**Comment by rafal-ch** [comment]
a summary of the discussion:
* sync slows down gradually (29456 blocks on Aug 11 --> 12918 blocks on Aug 14 --> 6859 blocks on Aug 16)
* as the sync slows down, the number of rejecting new incoming connection, limit for peer exceeded messages increases in the log
* after enabling debug, we see that lots of peers are demoted because failed to fetch finality signature (but also for few other reasons) - peers have been demoted 96200 and only 24467 promoted
* there is a correlation between slowdowns and blocks with low signatures (message from Joe on Slack)
* there are no "obvious" errors observed in the log, control logic behaves as expected

these lead to a conclusion that sync slows down due to difficulties in getting required finality


anyway, there might be other things at play:
* we agreed to double check if it is the first slowdown or it happened in the past (Joe has some numbers and a tool to crunch them) - to confirm that peer communication issues (pt. 2 above) don't slow down the sync on their own
* we agreed to shutdown the node for 10+minutes to clear all tarpitting and blocklist buffers and restart it - if the sync stays slow, we can exclude networking as the root cause
* no logs older than 1 week (and in particular no debug logs older than 1 day) - makes it difficult to clearly compare what was happening in the node when it was syncing quickly (for example, trie fetcher, historical sync stall, failed to fetch finality signature are all debug level messages)
* potentially more work in the forward sync, leaving less and less time for historical cycles? probably not a case, but only verified by checking that CPU usage doesn't increase

**Comment by RitaMAllenCA** [comment]
8.28.2023 we will (at least) cherry pick the fix from https://app.zenhub.com/workspaces/engineering-l1-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4202 into the branch to be released, iff we don't branch from dev.
