### ISSUE TITLE
Second VM: calling contracts

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4248]
As a follow up for previous ticket, second VM needs to be able to call previously stored contracts. Design around the possibility to call into 1.x stored contracts, also, figure out how to call into special ‘system contract’ addresses

**Comment by mpapierski** [comment]
- Much needed clean ups and consolidation of the code done into main repo
- New host function added that passes contract entrypoint's through a manifest object
- Entry points are defined by function pointer rather than exports which allows anonymous functions and other interesting design patterns.
- Calling contracts is still in progress, will continue in next ticket
