### ISSUE TITLE
Investigate and fix issue with missing transfers

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4268]
As per discussion in https://casper-labs-team.slack.com/archives/CDXBCHB6W/p1693793962701529.

**Comment by RitaMAllenCA** [comment]
This issue is with meta-data: One node has a summary; another node does not - however, both nodes have the same data.  The issue is with code that was built for a customer and supports a fast-track for the reporting - NOT the data.  The standard way to reconstruct the report data is working as expected and is the remediation if necessary.   This will be addressed no later than 1.5.3

**Comment by Fraser999** [comment]
The root cause of the issue is that writing the same set of execution results to `Storage` more than once has the effect of overwriting the valid value initially stored in `transfer_db` with an empty collection.  This is due to the `continue` [here](https://github.com/casper-network/casper-node/blob/a4b886629959acf6166b0617594c3f89929a1bec/node/src/components/storage.rs#L1476) resulting in the local variable `transfers` remaining empty and being written to `transfer_db` after the for loop has completed.

**Comment by MParlikar** [comment]
Exchanges are looking for the alt binary.  We need to provide a date when it will be ready.

**Comment by Fraser999** [comment]
@sacherjj or @cspramit should be able to answer that.  I don't believe there's any more dev work required on the new version other than a version bump PR.

**Comment by cspramit** [comment]
https://github.com/casper-network/casper-node/releases/tag/v1.5.2-alt

This is available
