### ISSUE TITLE
Design & implement reactor style tests for full Zug-compatible rewards process

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4317]
Follow up to #3914 and #4289

**Comment by rafal-ch** [comment]
Plan of attack:
1. Refactor out `effect_builder` from the reward calculation functions in order to be able to unit test them
2. Create a sunny-day mockreactor-like test to check if network is emitting rewards info on switch block
3. (but can happen in parallel with the two above) brainstorm with @fizyk20 and @AlexanderLimonov about potential testing scenarios (for example: validator going down or missing finality signatures, etc.)

**Comment by AlexanderLimonov** [comment]
Noted
