### ISSUE TITLE
Design a separate RPC server process for Condor ( Release 2.0 )

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4334]
We are aiming to make the RPC server in Condor / Release 2.0 a distinct and separate process. 
To achieve this, we need to collaborate with the Event-Sidecar team to explore the possibility of reusing elements from their existing architecture. 
The primary outcome of this ticket is the creation of a detailed design document outlining the approach and considerations for implementing the separate RPC server process in Condor.

**Comment by rafal-ch** [comment]
# RPC sidecar
## Motivation
* Allows for rapid iteration on the reporting side of the node, without requiring a full network upgrade
* `casper-node` does not need to implement a fully-fledged HTTP server
* security and availability concerns are moved to the sidecar process, so even in case of an attack, `casper-node` remains safe and operational
## Top-level requirements
* RPC sidecar provides RPC API identical to the one currently available in the `casper-node`
* it should include potential fixes and improvements to the RPC interface implemented for Condor
## Design choices
* `RPC sidecar` is expected to work on the same machine as `casper-node`
  * for `event-sidecar` the similar requirement changed during the development, so we need a confirmation what we expect from `RPC` sidecar - @EdHastingsCasperAssociation ?
* `RPC sidecar` does not store (cache) data in any local DB
* `RPC sidecar` communicates with `casper-node` via LMDB database
    * read data from LMDB to satisfy client requests
    * write data to LMDB to inform node that there is work to do (like `put-deploy`)
* `RPC sidecar` and `casper-node` will exchange `JSON` or `bytesrepr` based messages for increased legibility (see "Open design questions" below)
* The future `REST sidecar` will be just an extension of the `RPC sidecar`
## Open design questions
* Should the communication protocol with `casper-node` be:
  1. JSON-based? (better legibility, easier peek, lower performance, no need for additional tools)
  1. Binary-based? (no legibility, hard to peek, better perofmrance, possibly some new tool need to be designed to debug communication with `casper-node`)

__Opinions are equally divided here: please make a call__ @EdHastingsCasperAssociation .

## LMDB benchmark

### Tool:
    https://github.com/rafal-ch/lmdb_bench

### Stored payload:
    K - hash (32 bytes)
    V - 16..1024 bytes (random length)

### Notes:
- LMDB correctly handles writing from multiple threads, verified via
  - `lmdb_bench` tool using `-m` parameter
  - documentation at http://www.lmdb.tech/doc/index.html - _"(...)The library is fully thread-aware and supports concurrent read/write access from multiple processes and threads.(...)"_
- External readers are slower because we need to send K to them via IPC
- Node write speed is only slightly (if at all) affected by the number of readers
- Node read speed is slightly affected with 10 external readers (but this could be an effect of higher CPU demand)

### Conclusion:
   Single sidecar process have no noticeable impact on LMDB performance

### Results
#### 50000 writes and variable number of sidecars attached:
| Sidecars count | W     | W/s     | R internal   | R internal/s  | R external    | R external/s   | R total       | R total/s      |
|----------------|-------|---------|--------------|---------------|---------------|----------------|---------------|----------------|
| 0              | 50000 | 1470.49 | 305463820000 | 8484494597.53 | 0             | 0.00           | 305463820000  | 8484494597.53  |
| 1              | 50000 | 1470.49 | 306307270000 | 9008431606.39 | 4605827000    | 1354563916.17  | 352365540000  | 10362995522.57 |
| 2              | 50000 | 1470.48 | 307274930000 | 9036856218.60 | 70413310000   | 2070832652.52  | 377688240000  | 11107688871.12 |
| 10             | 50000 | 1428.43 | 299213870000 | 8548141543.00 | 2893564770000 | 82665289606.39 | 3192778640000 | 91213431149.39 |

#### 1000000 writes with 0 and 1 sidecar:
| Sidecars count | W       | W/s     | R internal   | R internal/s | R external  | R external/s | R total      | R total/s    |
|----------------|---------|---------|--------------|--------------|-------------|--------------|--------------|--------------|
| 0              | 1000000 | 1531.30 | 308413020000 | 472271332.99 | 0           | 0.00         | 308413020000 | 472271332.99 |
| 1              | 1000000 | 1543.11 | 300495150000 | 463696407.57 | 44408600000 | 68527256.71  | 344903750000 | 532223664.28 |


## Additional references
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/roadmap/110
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/governance/414
* https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/roadmap/56

## Resolved design questions

* Should `RPC sidecar` keep a local DB to cache data (similarly to `event sidecar`)?
  * __No__
* How should `RPC sidecar` communicate with the `casper-node`?
  * __Option 2__

| # | option         | description                                          | pros                                                                   | cons                                                                                                                                                                                                                                                                                                                                                                                                                 |
|---|----------------|------------------------------------------------------|------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1 | HTTP interface | `casper-node` still exposes an RPC or REST interface | - `RPC sidecar` can be located on different machine than `casper-node` | - `casper-node` is exposed to HTTP related attacks<br>- time required to implement this new, internal RPC endpoint                                                                                                                                                                                                                                                                                                   |
| 2 | DB access      | `RPC sidecar` uses direct access to storage          | - we can rip out the HTTP interface from the `casper-node` completely<br><br>(_as per comment, some basic interface for `put` methods must remain_)  | - potential performance problems when there are lots of `read` requests from the sidecar and `casper-node` tries to write to DB at the same time (behavior needs to be verified for LMDB as well as for potential, different DB backends [SQLite])<br>- it may not be possible to satisfy all queries solely with data taken from DB (i.e.: `/status` which needs to provide, for example, the `ReactorState` field)<br>- sidecar must understand the data extensibility (versioning) scheme - implementation must be kept in sync with the one in storage

* How should the internal RPC protocol be designed?
  1. utility-like (similarly to current one) - `RPC sidecar` can ask the `casper-node` for data and simply forward it to external client.
  2. data-access-like - `RPC sidecar` sends simple requests to store/retrieve elemntary data from `casper-node` (like a wrapped storage request) and builds the proper response to external client.
  * __not applicable as we don't plan to have RPC server in the node__

# Top level graph
![Untitled Diagram drawio](https://github.com/casper-network/casper-node/assets/88321181/53f5353f-a3ff-4565-85da-19ba282190ce)

**Comment by rafal-ch** [comment]
## WBS draft:
1. Create the fundamentals of the new `RPC sidecar` (_standalone app, reading config, parsing command line_)
2. Shadow current RPC interface (read-only)
   1. Make `RPC sidecar` capable of answering all current RPC requests
      1. Update node so that it stores all the necessary data in the DB (_currently, not all requests could be satisfied by looking into the DB, for example /status_).
      2. There are 17 "read" endpoints to mirror
   2. Disable the "read-only" RPC endpoints on the node
   3. Update all downstream apps (casper-test, NCTL, client, etc.)
3. Add the "write" part of the RPC interface to `RPC sidecar`
   1. `account_put_deploy` requests are stored in the LMDB
   2. modify node to be able to read and execute these requests
   3. Disable the "write" RPC endpoints on the node
   4. Update all downstream apps (casper-test, NCTL, client, etc.)
4. Documentation and instruction for `RPC sidecar`
