### ISSUE TITLE
Check the block hash mismatch issue

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4335]
One of the testnet validators encountered an issue with mismatched block hashes. We need to analyze logs and identify the cause. 

[Details:](https://casper-labs-team.slack.com/archives/CDX4YAHNW/p1696825301747249)

**Comment by alsrdn** [comment]
When block with height 2104256 era 10882 is executed by the node in question the resulting block hash is `1236..0499` which is wrong: https://testnet.cspr.live/block/590279d9b2cc02164c9fd643f8ee5f990f1e354a2416f2a67fd48a69a8704635

Unfortunately the log doesn't provide enough information for us to trace back why the hash was wrongly calculated. Since this block is also a switch block, it contains an era report with 100 new rewards and 100 new weights for the next era, so it's nearly impossible to try to reproduce that wrong hash since any of those values could be different and the log doesn't tell us which.

The duplicate height index error is probably caused by a failed attempt from the BlockAccumulator to store the block. The error shows that actually the call to store the header was made with the correct hash `5902..4635` which maybe means that the accumulator had the right block header for that height, but the wrong hash was already written to the index when the block got executed.

**Comment by rafal-ch** [comment]
Back to backlog until we have additional logs (Jiuhong will try to get them)

**Comment by Jiuhong-casperlabs** [comment]
Another operator reported similar issue 
```
Error: storage error: duplicate entries for switch block at era id era 12150: block hash 2ba1..38d4 / block hash 8efa..2fef
```
Debug logs are attached. 
[casper-node.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed68aeed3905573cbee32a137ea6a6275385133a/casper-node.txt)
[casper-node.stderr.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4d878d387ed574be88a558c92cf68a38190f810/casper-node.stderr.txt)

**Comment by SaiProServ** [comment]
Reviewed.

**Comment by SaiProServ** [comment]
This has been fixed.
