### ISSUE TITLE
Investigate flaky nightly test - "Upgrade after emergency upgrade"

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4365]
Nightly pipelines was fixed, but the it failed the next day. 
Details below :
Nightly Test Run Status: Failure
Author: casperlabs-bors-ng[bot]
Drone Build: #9376
Commit Link: d9783da61e

**Comment by rafal-ch** [comment]
Link to failed run: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/9435/1/4

**Comment by rafal-ch** [comment]
Another failed run: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/9492/1/4

**Comment by cspramit** [comment]
originally included in 1.5.4 but not a blocker thus moved to 1.6 and fix it. @alsrdn add comments and @rafal-ch talk to Ed

**Comment by alsrdn** [comment]
Added a PR that fixes the test. Description for the issue and the fix is also attached to the PR:

**Root cause:** In some runs this upgrade test was failing because it was hitting the 300 second timeout for syncing to genesis.
Sometimes when synchronizing historical blocks, the block synchronizer for node 1 was selecting 5 other nodes that did not have the finality signatures for that block (usually nodes 6-10).
Because the peer refresh interval was set to 90 seconds, the node did not have time to finish fetching the historical blocks if the situation described above happened for multiple blocks since the total timeout was 300 seconds.

**Fix:** Reduce the `block_synchonizer.peer_refresh_interval` config parameter for this test to 10s to allow it to become more lively and finish within the 300s timeout.
