### ISSUE TITLE
Merge and fix rewards reactor tests

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4443]
Need to merge the reactor tests for the rewards implementation with the reactor tests refactoring on feat-2.0, Felix had to rewrite quite a lot of stuff, and now some tests are failing. Felix is investigating this.

**Comment by real-felix** [comment]
After the merge, I had 3 bugs:

- The equivocator test doesn't pass on Zug, so I forced the used of Highway,
- There were an overflow error, so I had to use `U512` instead of `u64`,
- The helper function `run_until_stored_switch_block_header` doesn't work as expected with Highway, so I had to find a workaround.

**Comment by AlexanderLimonov** [comment]
Done, PR attached to https://github.com/casper-network/casper-node/issues/4401
