### ISSUE TITLE
Implement a DeployHash based log in GS to allow correlating messages between contract calls

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4460]
Address the requirements discussed [here](https://github.com/casper-network/ceps/pull/88#discussion_r1410061914):

**Comment by alsrdn** [comment]
Because pruning the per-transaction log entries is rather impractical, we decided not to include that change in the PR. The requirement for tracking message ordering across contracts is tracked by this new ticket: https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/casper-node/4545
