### ISSUE TITLE
Create a reactor test that checks that new 2.0 rewards are correctly distributed to inactive validators

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4621]
The scenario is described in [](https://github.com/casper-network/casper-node/issues/4611) and fixed by [PR](https://github.com/casper-network/casper-node/pull/4617),  but we don't have a test.

**Comment by fizyk20** [comment]
This is now tested by `run_withdraw_bid_network`.

The test was always doing a full unbond of one of the validators. However, until recently, it only run the network until the end of the era in which the unbond was submitted, in order to test if the bid has been removed. With PR #4719, the test has been extended to run for a few more eras, until the unbond has been processed. This had a side effect of running the network through the era in which the unbonded validator is no longer a validator, but still can (and does) receive rewards for the previous era, thus testing what this issue is about.

Thus, I think we can close this issue.
