### ISSUE TITLE
"validators_disconnect.sh" NCTL test passes correctly with Highway, but fails with Zug

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/casper-node#4837]
When Zug is enabled, network fails to resume operation after the previously disabled validators are started again

**Comment by devendran-m** [comment]
Follow-up point from L1 Daily on 17-Sep-24;
- Determine how much work remains to be done for the protocol state persistence.

**Comment by devendran-m** [comment]
Update from Bart in the L1 Daily on 18-Sep-24;

> Regarding the persistence of consensus state - what Zug persists isn't really the state, but it should be sufficient for resuming operation AFAICT. For Highway, the effort depends slightly on where we would want to store the state - storage, or some additional files similar to currently used unit files? Storage would be slightly more effort, but with it now being available in other components as an object (and not just through events/effects) it should not be too hard, either.

**Action:** As outlined by Ed, Bart should describe the state that needs to be persistent and define when it should be persistent. This detailed specification will allow the task to be delegated to other team members for implementation.

**Comment by fizyk20** [comment]
@devendran-m Those updates would fit #3904 better than this ticket, I think. This one is about a failing test and likely completely unrelated to the persistence of protocol state.

**Comment by devendran-m** [comment]
Please find the summary from the discussion between @fizyk20  and @EdHastingsCasperAssociation on the possible root cause and the next steps;

Issue: Validators in the ZUG environment increase their timeouts during a network stall. In some cases, timeouts reach 10 minutes, preventing recovery when disconnected validators rejoin.

Impact: Long timeouts during prolonged stalls (e.g., Mainnet outages) could make the network unrecoverable.

Proposed Solution:

- Bart suggested a hardcoded upper bound on timeouts, tested with 40 seconds, which resolved the issue.
- Ed inquired why an unbounded timeout was used initially. Bart suggested it was likely an oversight and tied to network adaptation to delays. 

Timeout Value Discussion:

- Ed suggested using a low upper bound (1 second), but Bart explained this would cause unnecessary round skipping.
- Bart proposed using triple the maximum round length (48 seconds) to account for slow validators.

Next Steps:
- Immediate fix: Set timeout upper bound to 48 seconds.
- Bart to continue the further investigation via a new discovery ticket.
