### ISSUE TITLE
Analyse Benchmark findings and design solution for optimising gas costs

### ISSUE THREAD

**Issue by devendran-m** [casper-network/casper-node#4951]
User story to further analyse and design solutions that optimise the gas costs and stack limiter functionalities within the Casper Network’s Wasm execution, to achieve predictable gas costs, and consistent throughput, and ensure node stability even under CPU-intensive operations.

To Do:

- [ ] Analyse of Benchmark Results
- [ ] Determine optimised Opcode costs
- [ ] Identify next steps for optimisation
- [ ] Document findings

This is a follow-up ticket of #4857

**Comment by mpapierski** [comment]
- Compared benchmarks results: benchmark wasm with gas injected, and without. Benchmarking without gas-injected code and validating with gas injectors give bad results (i.e. some computations easily exceed >60s) due to the non-deterministic nature of gas injector. I'm sticking to benchmarking wasm code with gas code injected to in attempt to ensure that each benchmarked block of opcodes contains amortized gas counter
- Examples from validation logic to ensure no computation exceeds 16s are positive and no wasm exceeds the allocated time with the exception that some CPU-intensive logic may trigger gas injector to be more prominent, and therefore these hit the gas limit sooner than expected (16s for fibonacci_rec(40) ~10s for primes). 
- Based on the observations having more predictable and deterministic gas counter could give us more predictable GasLimit validation across many workloads

Proposed changes includes lowering max gas per block to 200CSPR (from 3.3k) and the end result is 20x cheaper for most basic opcodes (bit, arithmetic, etc), and ~15x cheaper for control flow (call, call_indirect, br, etc.)
